### ISSUE TITLE
com.android.support:appcompat-v7:25.1.0 causes some problem

### ISSUE THREAD

**Issue by Devofure** [llollox/WDate-Wrapper-of-Date-Android#1]
Hi, could you remove the appcompat-v7 if you don't use it?

The support 25.1.0 causes some problems for my layout editor in Android Studio, so I need to use the 25.0.1 but your library make a version conflict.

**Comment by llollox** [comment]
Thank you for your suggestion!
This has been just fixed in this new version 1.0.4 that contains also other new features.
